'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("tetris.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_five() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_five", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_five_b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_five_b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_four() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_four", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_four_b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_four_b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_one() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_one", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_one_b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_one_b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_seven() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_seven", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_seven_b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_seven_b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_six() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_six", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_six_b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_six_b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_three() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_three", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_three_b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_three_b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_two() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_two", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property block_two_b() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("block_two_b", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_alien_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_alien_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_card_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_card_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_Cloud_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_Cloud_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_glasses_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_glasses_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_globe_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_globe_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_letter_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_letter_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_lightning_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_lightning_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_mail_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_mail_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_nbx_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_nbx_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_network_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_network_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_smile_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_smile_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property evenger_Spark_() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("evenger_Spark_", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Paused() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Paused", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property st_tng() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("st_tng", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Badge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Badge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Badge_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Badge_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Jem_Hadar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Jem_Hadar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Kazon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Kazon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Kazon_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Kazon_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Kazon_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Kazon_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Klaestron() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Klaestron", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Klingon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Klingon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Klingon_D7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Klingon_D7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Klingon_Flag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Klingon_Flag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Maquis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Maquis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Miradorn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Miradorn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Reliant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Reliant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Romulan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Romulan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Romulan_Scout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Romulan_Scout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Runabout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Runabout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Sailship() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Sailship", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Saratoga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Saratoga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Shuttle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Shuttle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Shuttle_Pod() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Shuttle_Pod", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Stargazer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Stargazer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Talaxian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Talaxian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Tarellian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Tarellian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Tholian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Tholian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Type_7_Shuttle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Type_7_Shuttle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Valkris() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Valkris", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Vidian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Vidian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Voyager() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Voyager", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Voyager_Shuttle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Voyager_Shuttle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Vulcan_Shuttle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Vulcan_Shuttle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Star_Trek___Warbird() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Star_Trek___Warbird", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Syllable___Avatars() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Syllable___Avatars", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Module
End Namespace
